-- 들어올때 중성화 X
-- 나갈때 중성화  O
WITH A AS(
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
)

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
INNER JOIN A
USING(ANIMAL_ID)
WHERE SEX_UPON_OUTCOME NOT LIKE '%Intact%'
