WITH RN AS(
SELECT 
    *,
    ROW_NUMBER() OVER (ORDER BY VIEWS DESC) AS RN
FROM USED_GOODS_BOARD
)

SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM RN
    INNER JOIN USED_GOODS_FILE 
    USING (BOARD_ID)
WHERE RN = 1
ORDER BY FILE_ID DESC